# Generated by Django 4.0.6 on 2022-07-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=255)),
                ('phone_numbers', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
